import { Link } from "react-router-dom";
import { ArrowRight, BrainCircuit, Check, Inbox, Ticket as TicketIcon } from "lucide-react";
import { useApp } from "@/context/AppContext";
import { Card, CardBody, CardHeader, PageHeader } from "@/components/ui/Card";
import { Badge, SeverityBadge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { ServiceIconBadge } from "@/components/ui/ServiceIcon";
import { timeAgo, confidenceLabel } from "@/lib/format";
import { cn } from "@/lib/utils";

/**
 * AI Insights — real rows from public.ai_insights produced by the Fusion AI
 * pipeline. When none exist yet the page says so; no analysis is invented.
 */
export function AiInsightsPage() {
  const { insights, now, acknowledgeInsight, actionInsight } = useApp();
  const highPriority = insights.filter((i) => i.severity === "critical" || i.severity === "warning").length;
  const actionable = insights.filter((i) => i.status === "new").length;

  return (
    <div>
      <PageHeader
        title="AI Insights"
        subtitle="Automated intelligence across your city's live telemetry and event streams."
        actions={<Badge tone={insights.length ? "info" : "neutral"} dot><BrainCircuit className="mr-1 h-3 w-3" /> Fusion AI</Badge>}
      />

      {insights.length > 0 && (
        <div className="mb-6 grid grid-cols-2 gap-4 lg:grid-cols-4">
          <Card className="p-5">
            <div className="text-[11px] font-bold uppercase tracking-widest text-ink-400">Total insights</div>
            <div className="mt-1 font-display text-[28px] font-bold text-pulse-600">{insights.length}</div>
          </Card>
          <Card className="p-5">
            <div className="text-[11px] font-bold uppercase tracking-widest text-ink-400">New / actionable</div>
            <div className="mt-1 font-display text-[28px] font-bold text-pulse-600">{actionable}</div>
          </Card>
          <Card className="p-5">
            <div className="text-[11px] font-bold uppercase tracking-widest text-ink-400">High priority</div>
            <div className="mt-1 font-display text-[28px] font-bold text-red-600">{highPriority}</div>
          </Card>
          <Card className="p-5">
            <div className="text-[11px] font-bold uppercase tracking-widest text-ink-400">Actioned</div>
            <div className="mt-1 font-display text-[28px] font-bold text-live-600">{insights.filter((i) => i.status === "actioned").length}</div>
          </Card>
        </div>
      )}

      {insights.length === 0 ? (
        <Card>
          <div className="flex flex-col items-center gap-2 px-6 py-16 text-center">
            <Inbox className="h-7 w-7 text-ink-300" />
            <h2 className="text-sm font-bold text-ink-700">No AI insights available.</h2>
            <p className="max-w-md text-xs leading-relaxed text-ink-400">
              Insights are generated by the Fusion AI pipeline from real telemetry and events.
              They will appear here automatically — nothing is generated in the browser.
            </p>
          </div>
        </Card>
      ) : (
        <div className="space-y-4">
          {insights.map((ins) => (
            <InsightCard
              key={ins.id}
              insight={ins}
              now={now}
              onAcknowledge={() => void acknowledgeInsight(ins.id)}
              onAction={() => void actionInsight(ins.id)}
            />
          ))}
        </div>
      )}
    </div>
  );
}

function InsightCard({
  insight: ins,
  now,
  onAcknowledge,
  onAction,
}: {
  insight: ReturnType<typeof useApp>["insights"][number];
  now: number;
  onAcknowledge: () => void;
  onAction: () => void;
}) {
  return (
    <Card className={cn(ins.severity === "critical" ? "border-red-200" : ins.severity === "warning" ? "border-amber-200" : "")}>
      <CardHeader
        title={
          <span className="flex flex-wrap items-center gap-2">
            <ServiceIconBadge service={ins.service} size="sm" />
            <span>{ins.title}</span>
            <SeverityBadge severity={ins.severity} />
          </span>
        }
        subtitle={`${timeAgo(ins.createdAt, now)} · Confidence ${confidenceLabel(ins.confidence)} (${Math.round(ins.confidence * 100)}%)`}
        action={<Badge tone={ins.status === "new" ? "info" : ins.status === "acknowledged" ? "warning" : "success"} dot>{ins.status}</Badge>}
      />
      <CardBody>
        <div className="grid gap-4 lg:grid-cols-[1.3fr_1fr]">
          <div>
            <SectionLabel>Observation</SectionLabel>
            <p className="mt-1 text-sm leading-relaxed text-ink-700">{ins.observation}</p>

            {ins.evidence.length > 0 && (
              <>
                <SectionLabel>Evidence</SectionLabel>
                <div className="mt-1 flex flex-wrap gap-2">
                  {ins.evidence.map((ev, i) => (
                    <span key={`${ev.label}-${i}`} className="rounded-md bg-ink-100 px-2 py-1 text-xs text-ink-700">
                      <span className="font-semibold">{ev.label}:</span> {ev.value}
                    </span>
                  ))}
                </div>
              </>
            )}

            <div className="mt-3 rounded-lg border border-pulse-100 bg-pulse-50 p-3 text-sm leading-relaxed text-pulse-900">
              <span className="font-bold">Recommendation:</span> {ins.recommendation}
            </div>

            {ins.devices.length > 0 && (
              <div className="mt-2 flex flex-wrap gap-2">
                {ins.devices.map((d) =>
                  ins.service === "lighting" ? (
                    <Link
                      key={d}
                      to={`/app/lighting/devices/${d}`}
                      className="inline-flex items-center gap-1 rounded-md border border-ink-200 px-2 py-1 text-xs font-semibold text-ink-600 transition-colors hover:border-pulse-300 hover:text-pulse-600"
                    >
                      {d} <ArrowRight className="h-3 w-3" />
                    </Link>
                  ) : (
                    <span key={d} className="rounded-md border border-ink-200 px-2 py-1 text-xs font-semibold text-ink-500">{d}</span>
                  )
                )}
              </div>
            )}
          </div>

          <div className="flex flex-col justify-end gap-2 border-t border-ink-50 pt-3 lg:border-l lg:border-t-0 lg:pl-4 lg:pt-0">
            <Button variant="outline" size="sm" disabled={ins.status !== "new"} onClick={onAction}>
              <TicketIcon className="h-4 w-4" /> Create ticket
            </Button>
            <Button variant="ghost" size="sm" disabled={ins.status !== "new"} onClick={onAcknowledge}>
              <Check className="h-4 w-4" /> Acknowledge
            </Button>
          </div>
        </div>
      </CardBody>
    </Card>
  );
}

function SectionLabel({ children }: { children: React.ReactNode }) {
  return <div className="text-[11px] font-bold uppercase tracking-widest text-ink-400">{children}</div>;
}