import { Link } from "react-router-dom";
import { BellOff, CheckCheck } from "lucide-react";
import { useApp } from "@/context/AppContext";
import { Card, PageHeader } from "@/components/ui/Card";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { timeAgo } from "@/lib/format";
import { cn } from "@/lib/utils";

const GROUPS = [
  { key: "critical", label: "Critical", cls: "border-red-200 bg-red-50/60" },
  { key: "warning", label: "Warnings", cls: "border-amber-200 bg-amber-50/60" },
  { key: "info", label: "Information", cls: "border-pulse-100 bg-pulse-50/40" },
] as const;

/**
 * Notifications — real rows from public.notifications for this organization.
 * Unread count comes from the database; marking read writes back to Supabase.
 */
export function NotificationsPage() {
  const { notifications, now, markNotificationRead, markAllNotificationsRead } = useApp();
  const unread = notifications.filter((n) => !n.read).length;

  return (
    <div>
      <PageHeader
        title="Notifications"
        subtitle="Alerts, AI recommendations and activity across your organization."
        actions={
          <>
            <Badge tone={unread > 0 ? "critical" : "success"} dot>{unread} unread</Badge>
            <Button variant="outline" size="sm" disabled={unread === 0} onClick={() => void markAllNotificationsRead()}>
              <CheckCheck className="h-3.5 w-3.5" /> Mark all read
            </Button>
          </>
        }
      />

      {notifications.length === 0 ? (
        <Card>
          <div className="flex flex-col items-center gap-2 px-6 py-16 text-center">
            <BellOff className="h-7 w-7 text-ink-300" />
            <div className="text-sm font-semibold text-ink-600">No notifications yet.</div>
            <p className="max-w-sm text-xs leading-relaxed text-ink-400">
              Notifications are generated by the platform when critical events occur or insights need attention.
            </p>
          </div>
        </Card>
      ) : (
        <div className="space-y-6">
          {GROUPS.map((g) => {
            const items = notifications.filter((n) => n.severity === g.key);
            if (!items.length) return null;
            return (
              <Card key={g.key} className={cn("border", g.cls)}>
                <div className="flex items-center justify-between border-b border-ink-100/60 px-5 py-3">
                  <div className="text-sm font-bold text-ink-800">{g.label}</div>
                  <Badge tone="neutral">{items.filter((n) => !n.read).length} new</Badge>
                </div>
                <div className="divide-y divide-ink-50">
                  {items.map((n) => (
                    <button
                      key={n.id}
                      onClick={() => void markNotificationRead(n.id)}
                      className={cn("flex w-full items-start gap-3 px-5 py-3.5 text-left transition-colors hover:bg-white/60", !n.read && "bg-white/40")}
                    >
                      <span className={cn("mt-1 h-2 w-2 shrink-0 rounded-full", n.severity === "critical" ? "bg-red-500" : n.severity === "warning" ? "bg-amber-500" : "bg-pulse-500")} />
                      <span className="min-w-0 flex-1">
                        <span className={cn("block text-[13px]", n.read ? "font-medium text-ink-700" : "font-bold text-ink-900")}>{n.title}</span>
                        {n.message && <span className="block text-xs text-ink-500">{n.message}</span>}
                        <span className="mt-0.5 block text-[10px] text-ink-400 tabular">{timeAgo(n.ts, now)}</span>
                      </span>
                      {!n.read && <span className="mt-1.5 h-2 w-2 shrink-0 rounded-full bg-pulse-500" />}
                      {n.actionUrl && (
                        <Link
                          to={n.actionUrl}
                          onClick={(e) => e.stopPropagation()}
                          className="shrink-0 self-center text-xs font-semibold text-pulse-600 hover:underline"
                        >
                          View
                        </Link>
                      )}
                    </button>
                  ))}
                </div>
              </Card>
            );
          })}
        </div>
      )}
    </div>
  );
}